word_set = { '🔥🥔': 'hot potato',
             '👶🚿': 'baby shower',
             '🌽🍞' : 'corn bread',
             '🍎🥧':'apple pie',
             '🧠⚰️':'braindead',
             '🦷🧚🏻':'tooth fairy',
             '🦻💍':'earring',
             '👨‍🍳📧':'cookie',
             '👽🧃':'alien juice',
             '💭🐲':'imagine dragons',
             '🐱🐠':'catfish',
             '👄👄':'tulips',
             '🐝🍃':'beliefs',
             '🕸️👁️':'website',
             '🪶🏋️‍♂️':'featherweight',
             '✂️👔':'cut ties',
             '🌊🧂':'sea salt',
             '⛷️😷':'ski mask',
             '🥇🎟️':'golden ticket',
             '🪝➖🚰':'hook line sinker',
             '🌃♣️':'nightclub',
             '🫶✉️':'love letter',
             '💍🐻':'ring bearer',
             '⭐️🐠':'star fish',
             '💡🏠':'lighthouse',
             '🚽📝':'toilet paper',
             '4️⃣🐜🐜':'france',
             '🐝🔛🗣️':'beyonce',
             '📰 📸':'newsflash',
             '🐜🧔':'antman',
             '🍕🛖':'pizza hut',
             }

word_set

